# SEE: https://github.com/gitleaks/gitleaks/#configuration

[extend]
useDefault = true # SEE: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[[rules]]
description = "IPv4"
id = "ipv4"
regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''

[rules.allowlist]
regexTarget = "match"
regexes = [
  # Exclude the private network IPv4 addresses as well as the DNS servers for Google and OpenDNS
  '''(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3}|0\.0\.0\.0|255\.255\.255\.255|8\.8\.8\.8|8\.8\.4\.4|208\.67\.222\.222|208\.67\.220\.220)''','''urn:oid:2.16.840.1.113883.2.1.3.2.4.18.24''',
]

[allowlist]
paths = ['''.terraform.lock.hcl''', '''poetry.lock''', '''yarn.lock''','''genomic-order-management-service-api.json''','''genomic-order-management-service-api.yaml''','''genomic-order-management-service-api-v2.yaml''','''genomic-order-management-service-api-v3.yaml''','''genomic-order-management-service-api-v4.yaml''','''genomic-order-management-service-api-v5.yaml''','''genomic-order-management-service-api-int-proxy.yaml''','''genomic-order-management-service-api-int-proxy-v2.yaml''','''genomic-order-management-service-api-int-proxy-v3.yaml''','''genomic-order-management-service-api-int-proxy-v4.yaml''','''genomic-order-management-service-api-int-proxy-v5.yaml''','''Genomic Order Management - ALPHA - API Collection - INT Environment.postman_collection.json''']


[[allowlists]]
description = "Hl7 UK Issued OIDs publicly available here: https://www.hl7.org.uk/standards/object-identifiers-oids/hl7-uk-issued-oids/"
regexTarget = "line"
regexes = [
    '''2.16.840.1.113883.2.1.3.2.4.18.24'''
]